apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: goapp-dev
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:dev-*
    repository.fluxcd.io/app: images.app
    tag.fluxcd.io/app: images.tag
spec:
  releaseName: goapp-dev
  chart:
    git: git@github.com:areshka515/goappChart.git
    path: goapp
    ref: master
  values:
    images:
      app: areshka515/goapp
      app_tag: dev-5212
    replicaCount: 1